_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": lr-AdamW
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": lr_abs
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": global_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 63
                - 79
                - 103
                - 105
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 63
                - 79
                - 103
                - 105
            "3":
                - 2
                - 7
                - 13
                - 14
                - 23
                - 55
                - 66
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.19.1
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
